# Generated by Django 5.0.14 on 2026-07-14 01:46

import apps.uploads.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("entidad", models.CharField(max_length=100)),
                ("entidad_id", models.CharField(max_length=50)),
                ("campo", models.CharField(max_length=100)),
                ("valor_anterior", models.TextField(blank=True)),
                ("valor_nuevo", models.TextField(blank=True)),
                ("motivo", models.TextField(blank=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acciones_auditadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de auditoría",
                "verbose_name_plural": "Registros de auditoría",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Carga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.FileField(upload_to=apps.uploads.models.ruta_carga)),
                ("archivo_nombre_original", models.CharField(max_length=255)),
                ("archivo_hash", models.CharField(db_index=True, max_length=64)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("VALIDADA", "Validada"),
                            ("RECHAZADA", "Rechazada"),
                        ],
                        default="PENDIENTE",
                        max_length=10,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("resultado_validacion", models.JSONField(blank=True, default=dict)),
                ("seccion", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "profesor_nombre",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("nivel", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "materia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cargas",
                        to="catalog.materia",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cargas",
                        to="catalog.periodo",
                    ),
                ),
                (
                    "ra",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cargas",
                        to="catalog.racatalogo",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cargas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Carga",
                "verbose_name_plural": "Cargas",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="Evaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seccion", models.CharField(max_length=20)),
                ("profesor_nombre", models.CharField(max_length=200)),
                ("nivel", models.PositiveSmallIntegerField()),
                ("actividad", models.CharField(max_length=300)),
                ("fecha_actividad", models.DateField()),
                (
                    "pct_aprobados_declarado",
                    models.DecimalField(decimal_places=3, max_digits=6),
                ),
                (
                    "pct_aprobados_recalculado",
                    models.DecimalField(decimal_places=3, max_digits=6),
                ),
                ("vigente", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "carga",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluacion",
                        to="uploads.carga",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluaciones",
                        to="catalog.materia",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluaciones",
                        to="catalog.periodo",
                    ),
                ),
                (
                    "ra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluaciones",
                        to="catalog.racatalogo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluación",
                "verbose_name_plural": "Evaluaciones",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="Criterio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=300)),
                ("orden", models.PositiveSmallIntegerField()),
                (
                    "evaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criterios",
                        to="uploads.evaluacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Criterio",
                "verbose_name_plural": "Criterios",
                "ordering": ["evaluacion", "orden"],
            },
        ),
        migrations.CreateModel(
            name="ResultadoEstudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grupo", models.CharField(blank=True, max_length=20)),
                ("nombre", models.CharField(max_length=200)),
                ("carrera", models.CharField(blank=True, max_length=200)),
                ("nota", models.DecimalField(decimal_places=3, max_digits=6)),
                (
                    "evaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados_estudiantes",
                        to="uploads.evaluacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado de estudiante",
                "verbose_name_plural": "Resultados de estudiantes",
                "ordering": ["evaluacion", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="ResultadoCriterio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("EXCELENTE", "Excelente"),
                            ("SATISFACTORIO", "Satisfactorio"),
                            ("INSATISFACTORIO", "Insatisfactorio"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "criterio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados",
                        to="uploads.criterio",
                    ),
                ),
                (
                    "resultado_estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados_criterios",
                        to="uploads.resultadoestudiante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado de criterio",
                "verbose_name_plural": "Resultados de criterios",
            },
        ),
        migrations.AddIndex(
            model_name="evaluacion",
            index=models.Index(
                fields=["periodo", "materia", "ra"],
                name="uploads_eva_periodo_5c6910_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="evaluacion",
            index=models.Index(
                fields=["periodo", "materia", "seccion", "profesor_nombre", "ra"],
                name="uploads_eva_periodo_e5078b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluacion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("vigente", True)),
                fields=("periodo", "materia", "seccion", "profesor_nombre", "ra"),
                name="evaluacion_vigente_unica",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="criterio",
            unique_together={("evaluacion", "orden")},
        ),
        migrations.AlterUniqueTogether(
            name="resultadocriterio",
            unique_together={("resultado_estudiante", "criterio")},
        ),
    ]
