# Generated by Django 5.0.14 on 2026-07-14 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Escuela",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, unique=True)),
                ("codigo", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "verbose_name": "Escuela",
                "verbose_name_plural": "Escuelas",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Periodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[("ABIERTO", "Abierto"), ("CERRADO", "Cerrado")],
                        default="ABIERTO",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Periodo",
                "verbose_name_plural": "Periodos",
                "ordering": ["-codigo"],
            },
        ),
        migrations.CreateModel(
            name="RACatalogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "RA de catálogo",
                "verbose_name_plural": "RAs de catálogo",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Materia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("nombre", models.CharField(max_length=200)),
                (
                    "escuela",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materias",
                        to="catalog.escuela",
                    ),
                ),
            ],
            options={
                "verbose_name": "Materia",
                "verbose_name_plural": "Materias",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Carrera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "escuela",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="carreras",
                        to="catalog.escuela",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carrera",
                "verbose_name_plural": "Carreras",
                "ordering": ["nombre"],
                "unique_together": {("nombre", "escuela")},
            },
        ),
        migrations.CreateModel(
            name="MateriaRA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel_esperado",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Nivel 1"), (2, "Nivel 2"), (3, "Nivel 3")]
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materia_ras",
                        to="catalog.materia",
                    ),
                ),
                (
                    "ra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materia_ras",
                        to="catalog.racatalogo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Materia ↔ RA esperado",
                "verbose_name_plural": "Catálogo Materia ↔ RA",
                "ordering": ["materia__codigo", "ra__codigo"],
                "unique_together": {("materia", "ra")},
            },
        ),
    ]
